version: "3.1"
services:
  app:
    build:
      context: .
    env_file:
      - flip.env
    command: bash -c "sleep && ./appmain"
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - testing
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=my_market
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_PORT=5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - testing

networks:
  testing:
